USE BANK;
------------------------------------------------------------------------------------------------------------------------
--                                     DATA TRANSFORMATION                                                            --
------------------------------------------------------------------------------------------------------------------------
/*
 CONVERT 2021 TXN_YEAR TO 2022
 CONVERT 2020 TXN_YEAR TO 2021
 CONVERT 2018 TXN_YEAR TO 2020
 CONVERT 2017 TXN_YEAR TO 2019
 CONVERT 2016 TXN_YEAR TO 2018
*/

/*``````````` FOR TRANSACTIONS TABLE````````````````````````````*/
UPDATE TRANSACTIONS
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE) = '2021';

UPDATE TRANSACTIONS
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE) = '2020';

UPDATE TRANSACTIONS
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE) = '2019';

UPDATE TRANSACTIONS
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE) = '2018';

UPDATE TRANSACTIONS
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE) = '2017';

UPDATE TRANSACTIONS
SET DATE = DATEADD(YEAR, 1, DATE)
WHERE YEAR(DATE) = '2016';

/*``````````` FOR CARD TABLE````````````````````````````*/
UPDATE CARD
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED) = '2021';

UPDATE CARD
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED) = '2020';

UPDATE CARD
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED) = '2019';

UPDATE CARD
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED) = '2018';

UPDATE CARD
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED) = '2017';

UPDATE CARD
SET ISSUED = DATEADD(YEAR, 1, ISSUED)
WHERE YEAR(ISSUED) = '2016';

/*
FILL THE NULL VALUE 
*/
UPDATE TRANSACTIONS
SET BANK = 'Sky Bank' WHERE BANK IS NULL AND YEAR(DATE) = 2022;

UPDATE TRANSACTIONS
SET BANK = 'DBS Bank' WHERE BANK IS NULL AND YEAR(DATE) = 2021;

UPDATE TRANSACTIONS
SET BANK = 'Northern Bank' WHERE BANK IS NULL AND YEAR(DATE) = 2019;

UPDATE TRANSACTIONS
SET BANK = 'Southern Bank' WHERE BANK IS NULL AND YEAR(DATE) = 2018;

UPDATE TRANSACTIONS
SET BANK = 'ADB Bank' WHERE BANK IS NULL AND YEAR(DATE) = 2017;

---------------------------------------------------------------------------------------------

